title: emilkarl.se
description: This is my description
markdown: rdiscount
auto: true
permalink: /:categories/:title/
pygments: true
lsi: false
paginate: 5
exclude:
   - Rakefile
   - github/build.rb
   - github/config.ru
   - logs

navigation:
  - text: blog
    url: /
    path: /index.html
  - text: about me
    url: /about/
    path: /about/index.html
  - text: things to do
    url: /todo/
    path: /todo/index.html