name: emilkarl
description: making web and wooden things
meta_description: "emilkarl - making wbe and wooding things"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 1
baseurl: /
domain_name: 'emilkarl.github.io'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://emilkarl.github.io'
author:         'Emil Karlsson'
